- .gitignore
- .npmignore
- .travis.yml
- README.md
- example.js
- index.js
- package.json
- test/yargs-parser.js
> make it so parsing features can be turned on and off with configuration

- README.md
- index.js
- package.json
- test/yargs-parser.js
Based on discussions with @sindresorhus, @isaacs, and @iarna, I've switched to using:
`require.main.filename`
I've thoroughly tested this approach with the following testing module:
https://www.npmjs.com/package/yargs-testing-module
And the following branch of yargs, which has integration tests for symlinks:
https://github.com/bcoe/yargs/pull/356
Using the two approaches outlined above, I've tested the following on `npm 2.x` and `npm 3.x`:
* global installs.
* running locally.
* symlinks.
* and nested dependencies.
Sorry for keeping this conversation going so long, I really want to be careful to get this right (`yargs@4.x` needs to be an improvement not a step backwards).
Reviewers: @sindresorhus, @jameswomack, @nexdrew
> based on various discussions I've switched to require.main.filename

- README.md
- index.js
- test/yargs-parser.js
This PR builds on top of @maxrimue #5 ; I wasn't able to push to his fork, so creating a new one. 
Summary: checks if value is not a number and assigns a `NaN`.
> New type number

- index.js
- test/yargs-parser.js
When a flag is encountered with nargs set, and = is used, the input args array is modified. This breaks recursive command parsing in yargs itself.
Copy the args before parsing and add a test which shows the problem.
Fixes https://github.com/yargs/yargs/issues/396
> Copy args before parsing

- index.js
- test/yargs-parser.js
This fixes [yargs/#383](https://github.com/bcoe/yargs/issues/383#issuecomment-185270189).
If passed as the first option, without grouping and value, an array option would not get defined as `eatArray()` does simply abort if it doesn't see any value passed. This fix makes `eatArray()` assign the array option the default value if no value is provided.
There might be a more elegant solution, though...
> Fix behaviour for arrays when passed with no value and as the first option

- index.js
- test/yargs-parser.js
I added a check for `configuration['dot-notation']` in `hasKey`, just like `setKey` already has. This way, if dot-notation is turned off, the keys will be joined. Therefore `hasKey` will be able to correctly tell if the key is in `obj`, without trying to check nested objects.
Without this fix, some errors occur when calling `applyDefaultsAndAliases` (which is the only method that calls `hasKey`) while dot-notation is disabled. For example:
- Values from the cli would fail to override defaults, if the defaults have dots.
- Values from the cli also fail to override aliases, if the aliases have dots.
> Join 'keys' in hasKey() when 'dot-notation' is turned off

- index.js
- test/fixtures/nested_config.json
- test/yargs-parser.js
It solves yargs/yargs#292.
`setConfig()` now checks the config object recursively, and calls `setArg()` for every nested key if that key isn't in argv or has the default value.
> Allow nested options in config files

- index.js
- test/yargs-parser.js
When handling the `--f=a b c` case, if the key of `--f=a` is in 'nargs' or 'arrays', then the value 'a' is added as the next item in 'args'. 
There's an issue with the call used for that: `args.splice(i + 1, m[1], m[2])`, where `m[1]` is the key and `m[2]` is the value. There should be a zero in place of `m[1]`, because the signature of splice is `array.splice(start, deleteCount[, item1[, item2[, ...]]])`, and we don't actually try to delete anything from 'args'.
An edge case error occurs if the key is actually a number. If so, that number of items will be deleted from args. (For example: Calling with `--1=a b` will result in `1 = ["a", null]`).
Note than the args.splice call is already used correctly when handling the `-f=a b c` case.
> Fix args.splice() when handling the case '--foo=xxx' with nargs or arrays

- index.js
I made some readability improvements:
- Replaced `letters[j]` with var `key`, in consistency with the rest of the code in that part.
- Replaced `arg.slice(j + 2)` with var `next`, in consistency with the rest of the code in that part.
- Created and used variable `next = args[i + 1]` when handling the last letter in 'arg'. This way it is more readable and looks exactly like the '--arg' case in line 150
> Improve code consistency when handling '-abc' case.

- index.js
- test/yargs-parser.js
Options with 'normalize' and 'array' no longer fail when passing more than 1 path.
The previous behavior of getter and setter is only applied when the option doesn't use the 'array' flag.
In the future, we can use ES2015's proxies to also apply the same effect of the getter and setter to all the elements in the array.
Note: For this to work, you need to set your option to 'array', it doesn't work with implicit arrays.
Closes yargs/yargs#430
> feat(normalize): allow normalize to work with arrays

- .npmignore
- package.json
This came up recently in https://github.com/yargs/yargs/issues/468#issuecomment-206442013.
Would be nice to trim the package size a bit by excluding tests, and I prefer whitelisting files in `package.json` over blacklisting files in `.npmignore`.
Here is the result of `npm pack` before and after this change:
```
x package/package.json
x package/.npmignore
x package/README.md
x package/example.js
x package/index.js
x package/appveyor.yml
x package/.travis.yml
x package/lib/tokenize-arg-string.js
x package/test/tokenize-arg-string.js
x package/test/yargs-parser.js
x package/test/fixtures/settings.js
x package/test/fixtures/config.json
x package/test/fixtures/config.txt
x package/test/fixtures/nested_config.json
x package/LICENSE.txt
x package/package.json
x package/README.md
x …
```
> Exclude tests from publication

- index.js
- test/yargs-parser.js
Inspired by this issue in minimist: https://github.com/substack/minimist/issues/44
It you have a boolean flag with a default to something that isn't a boolean. For example:
```javascript
var parsed = yargs(process.argv.slice(2), {
boolean: ['foo'],
default: {foo: null}
})
```
Then calling with `--foo` will result in `{"_": [], "foo": [null, true]}`.
I updated `setKey()` to avoid creating an array if the key in `argv` is in `flags.bools`. Previously, it only checked if the current value for the key in `argv` was a Boolean, but that didn't consider the case when a non-Boolean is set by default.
Note that setting a non-Boolean default for a Boolean key can be useful, as in the referenced issue, to find out if a key was explicitly set by the user in the CLI.
> Fix Boolean options with non boolean defaults

- index.js
- test/yargs-parser.js
Calling with a short option followed by a falsy value (like the empty string `""`) results in the value not applied to the flag.
For example, calling `-f ""` results in `{'_':[""], 'f':true}` instead of `{'_':[], 'f':""}`
I fixed this by updating the check to look like the one in the `--foo ""` case, where it works fine.
> Handle calling short option with an empty string as the next value.

- index.js
- test/yargs-parser.js
Calling this:
```javascript
var parsed = yargs(process.argv.slice(2), {
alias: {'foo': 'f'},
configuration: {'dot-notation': false}
})
```
With `--foo.bar "value"` results in the value being set to the key `'f.bar'`.
This fix removes the expansion of an alias of the first element of a dot-notation key, when dot-notation is disabled.
I simplified a bit the two loops that set aliases in `SetArg()`, because this new condition was making them a bit hard to follow. I moved one of the cases (calling `setKey()` for the full key if it doesn't have dot notation) from the second loop to the first loop. Here's how it looks now:
- The first loop calls `setKey()` for aliases of the full key, if the key key has dots or not.
- The second loop expands aliases of the first element in a dot-notation key, …
> Fix issue with dot-expansion disabled and an alias of the first element of a dot-notation key

- index.js
- test/yargs-parser.js
When calling `test.js -b aaafalseaaa`, and `b` is a boolean, the value of `'b'` is set to `false` and `'aaafalseaaa'` doesn't appear in `'_'`.
I fixed this by updating the regex to look like the one in the `--foo true` case, where it works fine.
> Fix Boolean flag when next value contains the strings 'true' or 'false'

- index.js
- test/yargs-parser.js
This was brought to by https://github.com/yargs/yargs/issues/435, about aliases not being set correctly to values set by `pkgConf`. (It also solves https://github.com/yargs/yargs/issues/423).
For aliases to be handled correctly, even considering transitive relationships, `pkgConf` values should be handled in yargs-parser, where most of the logic of aliases is. So, the solution here is to pass the object from the key in `package.json` to yargs-parser.
This is the first part of a solution that would later need yargs to pass the object to yargs-parser.
Here are some design considerations I made:
- I thought the best is to add a generic key to `opts` in yargs-parser, called `configObjects` that takes arbitrary objects and adds them to `argv`. So as to avoid coupling it with `pkgConf`. That …
> feat(configuration): Allow to pass configuration objects to yargs-parser

- index.js
- test/yargs-parser.js
It uses the '__' syntax to indicate nested properties, based on prior art from
https://github.com/indexzero/nconf#env and https://github.com/dominictarr/rc.
Closes yargs/yargs#332
> feat(environment): Support nested options in environment variables

- index.js
- test/yargs-parser.js
Based on https://github.com/yargs/yargs/issues/500
This was a bit tricky to figure out because default values were already being applied in line 274 but were then being overwritten immediately thereafter in a weird attempt to use the `increment` function to set a default value of 0 when no explicit default value is given. When an explicit default value _was_ given, the `increment` function would then inadvertently add/concat a `1` to the value. 😕 
Therefore the fix is comprised of these changes:
1. Let `applyDefaultsAndAliases` do its job of setting explicit defaults, see line 274
2. Apply a default of `0` to a count only when (a) no arg is given and (b) no explicit default is set, see new line 278
3. Only use the `increment` function when a count arg is actually given (not when setting a …
> fix(count): do not increment a default value

- index.js
- test/yargs-parser.js
When checking a group of options, if there is any number in the characters following the key being currently evaluated, then everything after the current key will be set as its value. This happens because the regex that checks for numbers is missing a `^` at the beginning, so strings like `'abc123'` are considered numbers.
An issue caused by this is that, for example, calling `-abc=123` results in `{"_": [], "a": "bc=123"}` instead of `{"_": [], "a": true, "b": true, "c": 123}`
> Fix issue with numeric character in group of options

- index.js
- test/yargs-parser.js
this should be considered a breaking change, as we can no longer define argument groups like `-123`; however let's simply amend the `3.x` release (since we haven't published the package yet).
fixes: #33
> fix: better parsing of negative values

- README.md
- index.js
- test/yargs-parser.js
Expect a coercion function to return or throw instead of calling a callback, to avoid any ambiguity that async functions might be supported.
> refactor: expect coerce functions to be synchronous

- index.js
- test/yargs-parser.js
> fix: address pkgConf parsing bug outlined in #37

- README.md
And other minor cleanup.
Closes #46.
> docs: clarify args as array of strings

- index.js
- test/yargs-parser.js
Fixes #50.
As a bonus, this also means coercion can apply to `argv._`. Here's an example:
```js
var parse = require('yargs-parser')
var argv = parse(process.argv.slice(2), {
coerce: {
_: function (arg) {
// do something special here
return arg
}
}
})
console.log(argv)
```
This works with an explicit `string: ['_']` option too (the coerce function would be guaranteed to be given an array of strings).
Note that coercion for implicit arrays (options parsed with multiple values but without `array` config) still happens per element.
> feat: coerce full array instead of each element

- index.js
- test/yargs-parser.js
This PR attempts to fix [yargs/yargs#599](https://github.com/yargs/yargs/issues/599).
While the newly added test now passes, two other tests now fail. I haven't figured out yet why they fail, hence this is a WIP PR.
> [WIP] Fix dot notation with coerce

- index.js
- test/yargs-parser.js
Fixes yargs/yargs#617
On studying the code I found that this bug is being caused by yargs-parser. I think my fix should solve this issue, though I'm not sure if something else breaks because of these changes.
I've tested this modified library with yargs and found that all test cases pass.
> fix: handle dot notation boolean options

- index.js
- test/yargs-parser.js
> fix: apply coercions to default options

- index.js
- test/yargs-parser.js
Lets you disable flattening of multiple array type values
```
yargsParser('-x a b -x c d', {array: ['x]})
// => {x: ['a', 'b', 'c', 'd']} // all flattened
```
```
yargsParser('-x a b -x c d', {array: ['x], configuration:{'flatten-duplicate-arrays': false}})
// => {x: [['a', 'b'], ['c', 'd']]} // multiple nested arrays
```
```
yargsParser('-x a b', {array: ['x], configuration:{'flatten-duplicate-arrays': false}})
// => {x: ['a', 'b']} // still a flat single array when no duplicates
```
fixes [yargs#688](https://github.com/yargs/yargs/issues/688)
includes #67
>  	feat: allow not to flatten duplicate array types

- index.js
- test/yargs-parser.js
edge case discussed in https://github.com/yargs/yargs/issues/716
> fix: inner objects in configs had their keys appended to top-level key when dot-notation was disabled

- index.js
- test/yargs-parser.js
fixes #74 
Fix with tests for following possible cases:
duplicate=false, flatten=false
type=array
[-x 1 2 3]          => [1, 2, 3]
[-x 1 2 3 -x 2 3 4] => [2, 3, 4]
type=string/number/etc
[-x 1 -x 2 -x 3]    => 3
duplicate=false, flatten=true
type=array
[-x 1 2 3]          => [1, 2, 3]
[-x 1 2 3 -x 2 3 4] => [2, 3, 4]
type=string/number/etc
[-x 1 -x 2 -x 3]    => 3
duplicate=true, flatten=true
type=array
[-x 1 2 3]          => [1, 2, 3]
[-x 1 2 3 -x 2 3 4] => [1, 2, 3, 2, 3, 4]
type=string/number/etc
[-x 1 -x 2 -x 3]    => [1, 2, 3]
duplicate=true, flatten=false
type=array
[-x 1 2 3]          => [1, 2, 3]
[-x 1 2 3 -x 2 3 4] => [[1, 2, 3], [2, 3, 4]]
type=string/number/etc
[-x 1 -x 2 -x 3]    => [1, 2, 3]
The numbers are also preserved as numbers.
> fix: flatten/duplicate regression

- index.js
- test/yargs-parser.js
BREAKING CHANGE: environment variables now take precedence over config file values.
see: https://github.com/yargs/yargs/issues/627
CC: @jaridmargolin
> fix: environment variables should take precedence over config file

- README.md
- index.js
- test/yargs-parser.js
Implements yargs/yargs/issues/682
> Add -- option which controls how arguments after -- flag are returned.

- .travis.yml
as promised, we're going to be dropping Node 0.10/0.12 support in yargs@8.
> chore: drop support for Node 0.10/0.12

- README.md
- index.js
- test/yargs-parser.js
BREAKING CHANGE: rather than placing arguments in "_", when parsing is stopped via "--"; we now populate an array called "--" by default.
I've changed the configuration option to be named `populate--` rather than `--`; as this better fits with the naming conventions of our other configuration settings.
CC: @ruimarques
> feat: when parsing stops, we now populate "--" by default

- index.js
- test/yargs-parser.js
we should be defaulting `--` to `undefined`, rather than an empty array; this behavior is closer to how the `array` type works.
> fix: default '--' to undefined, allowing for smoother transition in yargs

- README.md
- index.js
- test/yargs-parser.js
BREAKING CHANGE: populate-- defaults to false, based on discussion at npm today.
> chore: revert populate-- logic

- README.md
- index.js
- test/yargs-parser.js
This PR adds a configuration setting `negation-prefix` which allows the prefix used in boolean negation to be specified. The default value of `no-` ensures backward compatibility.
**Justification:** I am using `yargs-parser` to parse the command lines of 3rd party programs and not all of them follow the `--no-foo` convention. Some programs seem to use `--nofoo` instead of `--no-foo`.
> Allow configuration of prefix for boolean negation

- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
> Do not remove quotes when tokenizing a non-option string

- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
> Fix: Ignore multiple spaces between arguments.

- index.js
- package.json
- test/yargs-parser.js
Begins to address issues discussed in https://github.com/yargs/yargs/issues/96, moving us towards
* don't magically parse numbers larger than `Number.MAX_SAFE_INTEGER`.
* pull number parsing logic into `maybeCoerceNumber`.
* fix broken `parse-numbers = false` logic.
> feat: reworking how numbers are parsed

- index.js
- test/yargs-parser.js
> Fix: Allow null config values

- .gitignore
This pull request adds `.idea` directory and `package-lock.json` file to `.gitignore` as it's [done in yargs](https://github.com/yargs/yargs/blob/master/.gitignore).
> .idea directory and package-lock.json are added to .gitignore as it's done in yargs

- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
> fix: tokenizer should ignore spaces at the beginning of the argString

- index.js
- test/yargs-parser.js
Fixes #76 
Fixes yargs/yargs#923
> fix: only run coercion functions once, despite aliases. (#76)

- index.js
- test/yargs-parser.js
due to a bug in our bounds checking logic, scientific notation could be entered greater than MAX_INTEGER.
fixes: https://github.com/yargs/yargs/issues/1017
see: https://github.com/yargs/yargs/pull/1019
> fix: scientific notation circumvented bounds check

- index.js
- test/yargs-parser.js
This is a fix for yargs/yargs#817.
> Merge with config when array

- README.md
- index.js
- package.json
- test/yargs-parser.js
@markbirbeck went ahead and made this feature configurable; you can enable it on your library by adding a `yargs` stanza to a package.json with `combine-arrays: true`.
> feat: make combining arrays a configurable option

- index.js
- package.json
- test/yargs-parser.js
BREAKING CHANGE: arguments of form --foo, -abc, will no longer be consumed by nargs
This is in prep for replacing the crufty legacy method `requiresArg` with nargs(1).
CC: @evocateur for review
> feat: narg arguments no longer consume flag arguments

- index.js
- test/yargs-parser.js
Fix #116
`boolean` flags defined without a `default` value will now behave like other option type and won't be set in the parsed results when the user doesn't set the corresponding CLI arg.
Previous behavior:
```js
var parse = require('yargs-parser');
parse('--flag', {boolean: ['flag']});
// => { _: [], flag: true }
parse('--no-flag', {boolean: ['flag']});
// => { _: [], flag: false }
parse('', {boolean: ['flag']});
// => { _: [], flag: false }
```
New behavior:
```js
var parse = require('yargs-parser');
parse('--flag', {boolean: ['flag']});
// => { _: [], flag: true }
parse('--no-flag', {boolean: ['flag']});
// => { _: [], flag: false }
parse('', {boolean: ['flag']});
// => { _: [] } => flag not set similarly to other option type
```
> fix: do not set boolean flags if not defined in `argv`

- README.md
- index.js
- test/yargs-parser.js
If `true`, add a placeholder for each known key for which the corresponding CLI argument is not set.
The default value for the placeholder is `undefined`.
Follow up to https://github.com/yargs/yargs/pull/1105
> feat: add `set-placeholder-key` configuration

- index.js
- test/yargs-parser.js
This fixes issue #77
This *is* a breaking change
> Camel-Case-Expansion: alias by Property names, not Pathes

- index.js
- test/yargs-parser.js
When `requiresArg` was used together with `array`, only the first
argument of the array would end up being parsed. With this change
things work as expected.
The `requireArg` option sets the `nargs` options to `1`, so only
one additional argument will be parsed. The problem was that that
parsing step was checked before the array parsing one. The solution
is as simple as flipping those if conditions and check if its an
array first, hence ignoring the `nargs` option.
Fixes https://github.com/yargs/yargs/issues/1170.
> fix: make requiresArg work with arrays

- README.md
- index.js
- test/yargs-parser.js
> Add option to allow coercion of array items

- index.js
- test/yargs-parser.js
Hi, thank you for a great library :).
I'm using `yargs-parser` in a lot projects, one of them is [redrun](https://github.com/coderaiser/redrun) (CLI tool to run multiple npm-scripts fast). It has a couple 1 char aliases:
```
Usage: redrun [...tasks] [options] [-- ...args]
Options:
-p, --parallel          run scripts in parallel
-P, --parallel-calm     run scripts in parallel and return zero exit code
```
After updating to [v11.0.0](https://github.com/yargs/yargs-parser/blob/master/CHANGELOG.md#1100-2018-10-06) some of [my tests has failed](https://github.com/coderaiser/redrun/blob/v7.0.0/test/redrun.js#L273-L282), here is [parsing](https://github.com/coderaiser/redrun/blob/v7.0.0/lib/cli-parse.js#L61-L95): 
```js
const yargsParser = require('yargs-parser');
const result = …
```
> fix: handling of one char alias as a camelCase

- index.js
- test/yargs-parser.js
This reverts commit 77ae1d4e1c2590eeca025952671fff935ab7e884.
Prior to this commit, those wishing to require that an `array`-type option has a nonzero amount of arguments could use the `check()` function for validation.
The commit removed the ability to use `nargs` in conjunction with `array`-type options.
After this commit, those wishing to limit the number of values an `array`-type option accepts have no viable workaround.  This *also* has the implication that such an option cannot be used prior to a positional option, because it's ambiguous:
```bash
$ script --foo bar baz quux
```
**UPDATE**: Previous to #136, the above example was still an issue, but `nargs(1)` or `requireArg()` was a viable workaround; it no longer is.
> Revert "fix: make requiresArg work in conjunction with arrays (#136)"

- .gitignore
- test/yargs-parser.js
I wanted to see in what order `configObjects` were applied, so I wrote a test.
I also added a commit to add `coverage/` to `.gitignore`, since running `npm test` creates it.
> add test for config object priority

- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
A string such as "hello '' world" would parse into ["hello", undefined, "world"].
This would add a catch for that, ensuring that an empty string is pushed
instead, and adds associated tests.
> Ensure empty string is added into argv._

- example.js
- index.js
- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
- test/yargs-parser.js
addresses #145 and related issues, by no longer consuming quotes during the string tokenization phase, we now instead cleanup strings post-hoc.
BREAKING CHANGE: quotes at beginning and end of argument values are now removed.
> fix: better handling of quoted strings

- index.js
- test/yargs-parser.js
If default values are provided for an option, they will now be used if a flag is provided with no right-hand value.
fixes: #144 
BREAKING CHANGE: a flag with no right-hand value no longer populates defaulted options with undefined.
> feat: default value is now used if no right-hand value provided for numbers/strings

- index.js
- test/yargs-parser.js
This causes boolean arguments to honor an narg setting of zero.
Fixes #170
> feat: Support boolean which do not consume next argument.

- README.md
- index.js
- test/yargs-parser.js
Enabling these options cause redundant keys to be removed from the
results.  This can be useful when printing the results for debugging as
it reduces the amount of information to look at.
> feat: Add `strip-aliased` and `strip-dashed` configuration options.

- README.md
closes #159 
The example of "halt-at-non-option" is incorrect.
If disabled: `node example.js -a run b -x y`
- actual: { _: [ 'run', 'b', 'y' ], a: true, x: true }
- correct:  { _: [ 'b' ], a: 'run', x: 'y' }
If enabled: `node example.js -a run b -x y`
- actual: { _: [ 'run', 'b', '-x', 'y' ], a: true }
- correct: { _: [ 'b', '-x', 'y' ], a: 'run' }
> README: fix example of "halt-at-non-option"

- README.md
> README: add description of "opts.configObjects"

- index.js
- test/yargs-parser.js
fix: should populate "_" when given config with "short-option-groups" false
issues: https://github.com/yargs/yargs-parser/issues/177
> fix: should populate "_" when "short-option-groups" is false

- lib/tokenize-arg-string.js
- test/tokenize-arg-string.js
closes #166 
`args = parse( ['--p', 2] );` throws a `TypeError`
- extend "lib/tokenize-arg-string.js": convert all values to `string`'s
- add one test
> Fix: "TypeError: next.match is not a function" with "number" values

- index.js
- test/yargs-parser.js
#closes #118 
```js
var args = parse(
'foo -p x y', {
narg: { p: 2 },
'duplicate-arguments-array': false,
}
}
);
console.log(args);         //  { _: [ 'foo' ], p: 'y' }    <== incorrect
```
the correct output should be:
- 'foo -p x y' => { _: [ 'foo' ], p: [ 'x', 'y' ] }
- 'foo -p x y -p a b' => { _: [ 'foo' ], p: [ 'a', 'b' ] }
- 'foo -p x y z -p a b c' => { _: [ 'foo' ], p: [ 'a', 'b', 'c' ] }
- fix `setKey()`: `nargs` has higher priority than `duplicate`
- add one test
> Fix: "duplicate-arguments-array" should not interfere with "option.nargs"

- index.js
- test/yargs-parser.js
closes #176 
- `applyCoercions()`: the return value of the coerce function is now checked by calling `maybeCoerceNumber()`, wether it should be converted to type number.
- `maybeCoerceNumber()`: currently return values of coerce functions are not converted to type number.
I deleted this restriction <== **THIS HAS TO BE CONFIRMED**
- extend one existing test
> Coerce function returns option of type "number" as "string"

- index.js
- test/yargs-parser.js
```js
var args = parse('--file --file', {
boolean: ['file'],
'duplicate-arguments-array': true,
'flatten-duplicate-arrays': false
}
})          // { _: [], file: true }
```
The result is incorrect, it should be: `{ _: [], file: [ true, true ] }`
The root problem can be found in an incorrect `boolean` handling of default values and hence a bug fix at the wrong place.
PR #119 shows the `boolean` option behavior when **no default value** is set.
```
var parse = require('yargs-parser');
parse('--flag', {boolean: ['flag']});
// => { _: [], flag: true }
parse('--no-flag', {boolean: ['flag']});
// => { _: [], flag: false }
parse('', {boolean: ['flag']});
// => { _: [] }                     => flag not set similarly to other option type
```
**When a default value is set:**
``` …
```
> Fix "boolean" flag with "duplicate-arguments-array"

- index.js
- test/yargs-parser.js
```js
var args = parse(['--file', 'one', '--nr', '5', '2', '--nr', '4'], {
array: [{ key: 'nr', number: true }],
configObjects: [{nr: ['1','2','3']}],
'combine-arrays': true,
'flatten-duplicate-arrays': false
}
})     // { _: [], file: 'one', nr: [ NaN, 4, NaN ] }
```
The result is incorrect, it should be: { _: [], file: 'one', nr: [ [ 5, 2 ], [ 4 ], [ 1, 2, 3 ] ] }
> Fix: number[] - maybeCoerceNumber(): processing of number typed arrays

- index.js
- test/yargs-parser.js
Currently the parser handles `opts.narg` before `opts.array` and therefore `eatArray()` is not restricted by the `opts.narg` value.
The edge case `opt.narg === 0` is handled in a different way since `checkAllAliases()` returns `false` instead of value `0`. Case `opt.narg === 0` should be handled the same way as `opt.narg > 0 ` to keep the distinction between `opts.narg` and `opts.array` options clear and clean.
- `checkAllAliases()`: fixes case of `opt.narg === 0` and returns now `0` instead of `false`
- `eatNargs()`: sets now default values in case of `opt.narg === 0`
Note: the default value of a string typed option is currently an empty string (`defaultForType()`).
I would have expected `undefined`.
> Fix: eatNargs() for 'opt.narg === 0' and boolean typed options

- index.js
- test/yargs-parser.js
```js 
var args = parse('--file --file', {
array: ['file'],
boolean: ['file'],
'duplicate-arguments-array': true,
'flatten-duplicate-arrays': false
}
})      // { _: [], file: [ [], [], [] ] }
```
The result is incorrect, it should be: **{ _: [], file: [ [true], [true] ] }**
- `eatArray()` is called even for flags without arguments. This enables to set:
- `boolean` with short syntax ('--bool --bool') which carries its implicit value `true`
- default values given by `opts.default` for all type of options (except `boolean`)
- the fallback default value for all type of options is an empty array `[]`. 
- `eatArray()`: remove the `multipleArrayFlag` logic. The "duplicate array" pattern is already handled within `setKey()` depending on the `flatten-duplicate-arrays` …
> Fix: boolean[] -  eatArray() with boolean typed arrays and user defaults

- index.js
- test/yargs-parser.js
`setConfigObject()` does not recognise aliases and camel-cased flags when testing for array type.
closes #196
> Fix: setConfigObject() with array typed options and alias/camel-case

- README.md
- index.js
- test/yargs-parser.js
Fixes yargs/yargs#1243
All new code is covered in tests. It shouldn't make any difference, but I used the Wallaby.js VSCode extension for test running and coverage, instead of the npm scripts.
I tried to match the existing code style as well as possible, but please feel free to fix any issues I created.
> feature: add configuration option "collect-unknown-options"

- README.md
- index.js
- test/yargs-parser.js
@bcoe: since I don't seem to be able to re-open #181, I'm creating a new pull request.  It turns out that the issue I was having with the command parsing after the previous pull request was that it uses an array arg, rather than the `_` array.  I've updated my feature from `collect-unknown-options` to `unknown-options-as-args` so that it can also cover this case.
I've tested this in the script I plan to use it in, and it works as I would expect now.
> feat!: rework `collect-unknown-options` into `unknown-options-as-args`, providing more comprehensive functionality

- index.js
- test/yargs-parser.js
This fixes an edge case created by @henderea's #181 and #202 when `unknown-options-as-args` and `populate--` are _both_ `true`. I encountered it when attempting to upgrade Lerna from yargs v12 to yargs latest (v14).
In the process of identifying the fix, I realized I probably shouldn't be using `populate--` 🤣 (the new `unknown-options-as-args` is much better for my use-case!)
> fix(unknown-options-as-args): '--' is not an unknown option

- index.js
- test/yargs-parser.js
This pull request fixes some issues with negative numbers containing decimal places.  It also adds support for negative numbers that don't have a leading 0, such as `-.1`.
Fixes yargs/yargs#1204
> support negative numbers with decimal places

- index.js
- test/yargs-parser.js
closes #205 
Default values for array typed options can be set now as arrays or as primitive values.
> Fix: array option with array default value

- index.js
- test/yargs-parser.js
```js
var args = parse('-f foo baz -f', {
array: ['f'],
count: ['f'],
'duplicate-arguments-array': true,
'flatten-duplicate-arrays': false
}
})       //  { _: [], f: [ [ [Function: increment], [Function: increment] ], [] ] }
```
The result is incorrect, it should be:  **{ _: [ 'foo', 'baz' ], f: 2}**
```js
var args = parse('-f foo baz -f', {
narg: {'f': 1},
count: ['f']
})     // { _: [ 'baz' ], f: 1 }
```
The result is incorrect, it should be: **{ _: [ 'foo', 'baz' ], f: 2 }**
A configuration `opts.count` plus `opts.array` or `opts.narg` does not make sense. Nevertheless this combination can be set by the user.
- ~~we delete `opts.array` / `opts.narg` settings before parsing~~
- we populate `error` with an error object (but don't throw one)
> feat!: throw exception if incompatible narg/count or narg/array options are used

- README.md
- index.js
- test/yargs-parser.js
closes #203 
`Parse.detailed()` returns an additional object `defaulted` which contains any new argument created by `opts.default`. This argument has not been specified by the user.
` defaulted`: `{ foo: true }`
` defaulted` does not include:
- defaulted aliases
- an option specified by the user on CLI/config/configObjects but without value
> feature: defaulted functionality

- CHANGELOG.md
- package.json
This reverts the CHANGELOG entry for 16.0.0, which we did not create a GH release for, we're instead adding the release details to `16.1.0`.
Release-As: 16.1.0
> revert: revert 16.0.0 CHANGELOG entry

- index.js
Closes #226.
Fixes 3 bugs in hasAnyFlag:
1. using `...` inside `concat` flattens all arrays. So if `flags.string` (for example) is an array of string, `toCheck ` does not contain this array of string, but the strings directly. And a few lines below, if `flag` is a string, `flag[repeat]` evaluates to true (as with any method names of String.prototype)
2. once corrected the first bug, if `flag` is now an array, `flag[some]` evaluates to true (Array.prototype...)
3. same thing for the methodes of Object.prototype if `flag` is an object
By the way, yargs-parser crashes when passing a `--toString` option: I thing this kind of bug has to be tracked everywhere in the code (I will open another issue for this).
> fix: address bugs with "uknown-options-as-args"

- index.js
- lib/tokenize-arg-string.js
- package.json
- test/fixtures/config.json
- test/tokenize-arg-string.js
- test/yargs-parser.js
BREAKING CHANGE: objects used during parsing are now created with a null
prototype. There may be some scenarios where this change in behavior
leaks externally.
fixes #228
> fix!: support keys that collide with object prototypes

- index.js
- package.json
- test/yargs-parser.js
There was a small regex bug that was causing the bug described in #231.
fixes #231
> fix: unknown options terminated with digits now handled by unknown-options-as-args

- index.js
- test/yargs-parser.js
This reverts behavior to match yargs@14. If an argument is configured as a `bool` we will not coerce it into an array.
@SimenB could I get you to try out this branch if you have a moment.
Refs: https://github.com/facebook/jest/issues/9517
BREAKING CHANGE: this reverts parsing behavior of booleans to yargs@14
> feat!: boolean arguments will not be collected into an implicit array

- index.js
- test/yargs-parser.js
by switching the order of parsing `nargs` and `array`, but enforcing the `nargs` count in `array`, we can address the issue discussed in https://github.com/yargs/yargs/issues/1098.
Refs: https://github.com/yargs/yargs/issues/1098
> fix: array should take precedence over nargs, but enforce nargs

- README.md
- index.js
- test/yargs-parser.js
Setting `nargs-eats-options` to `true` can now be used to put `yargs-parser` back to its pre `v9` behavior.
fixes: #232
> feat: introduce nargs-eats-options config option

- index.js
- test/yargs-parser.js
This was breaking upstream behavior in yargs (and in turn mocha), because the parsed options object is iterated over in yargs and appended to another object:
```bash
mocha init <path>
create a client-side Mocha setup at <path>
Positional Arguments
path                                                       [string] [required]
Other Options
--help, -h     Show usage information & exit                         [boolean]
--version, -V  Show version number & exit                            [boolean]
✖ ERROR: Missing required argument: path
```
> fix: normalized keys were not enumerable

- index.js
- test/yargs-parser.js
Introduces special handling of NaN, which yargs will use rather than 1 to indicate that
an argument has a required value following the flag.
BREAKING CHANGE: the narg count is now enforced when parsing arrays.
---
This is in reaction to https://github.com/mochajs/mocha/pull/4196, https://github.com/yargs/yargs/issues/1098, and https://github.com/yargs/yargs/issues/1570. It will eliminate ambiguity in `requiresArg` vs., `nargs = `, by moving `requiresArg` to using the special `NaN` value for `nargs`.
> feat!: NaN can now be provided as a value for nargs, indicating "at least" one value is expected for array

- index.js
- test/yargs-parser.js
Following up from the discussion from: https://github.com/yargs/yargs/issues/1454 even though there are plenty of valid usecases for single-digit aliases and many well stablished examples, it is still completely unsupported on yargs-parser.
As brought up by @benjie many standard unix tools uses such pattern, after reading his examples and giving it some thought, I ended up classifying them in two groups:
- Single-digit shortcut flags, which behave as booleans modifying behavior within the tool:
- `xargs -0`
- `kill -9`
- `gzip -1`
- `rsync -6`
- Numeric shortcut params, which behave as actual number configs:
- `git log -3`
- `grep -3`
This changeset introduces the support to the first group described, in which single-digits can be used as alias in the context of boolean flags.
/cc @bcoe …
> feat: introduce single-digit boolean aliases

- index.js
- test/fixtures/config.json
- test/yargs-parser.js
addresses potential for prototype pollution.
> fix: __proto__ will now be replaced with ___proto___ in parse

- index.js
- test/yargs-parser.js
Fixes #261 
As a side effect, this PR also enforces narg 0 for -o=value and --option=value, with a new "Argument unexpected for: %s" error (was silently ignored up to now).
> fix(array, nargs): support -o=--value and --option=--value format

- index.js
- test/yargs-parser.js
> fix(setArg): options using camel-case and dot-notation populated twice

- index.js
- package.json
- test/fixtures/config.json
- test/yargs-parser.js
GitHub won't let me create a draft against another tag so this diff is going to be really weird.
I'm guessing the best way to work on this would be to branch `v5.0.0` tag into a branch and then PR against that. Once it is merged and released, the branch can be cleaned up since the tag will point to the new version.
Drafting while WIP.
> fix: back-porting prototype fixes for *really* old version

- package.json
Update decamelize dependency to get latest TypeScript definition as part of #265.
Package | Type | Update | Change
-------- | ----- | ------- | --------
[decamelize](https://github.com/sindresorhus/decamelize/) | dependencies | major | [`^1.2.0` -> `^3.2.0`](https://github.com/sindresorhus/decamelize/compare/v1.2.0...v3.2.0)
> fix(deps): update dependency decamelize to v3

- .github/workflows/ci.yaml
- README.md
- index.js
- package.json
- test/yargs-parser.js
This skips the EOL Node 8, and moves us to Node 10 as the supported Node.js version for yargs-parser.
_Note: we should complete the TypeScript conversion before we release this major version of the library._
TODO:
Refs #272
> build!: drops Node 6. begin following Node.js LTS schedule

- package.json
This PR downgrades devDependency eslint from v7.0 to v6.8.0 and resolves the npm install warnings. In #272 I had matched the semver used for yargs dependencies but yargs had prematurely upgraded eslint.
```text
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.14.3 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```
> chore(deps): update devDependency eslint to 6.8

- index.ts
- lib/yargs-parser-types.ts
This gets the TypeScript version of yargs-parser working with yargs.
> fix(types): switch back to using Partial types

- browser.js
- deno.ts
- lib/index.ts
- lib/yargs-parser-types.ts
- test/deno/yargs-test.ts
- test/string-utils.cjs
Exposes camelCase and decamelize methods, so that they can be used upstream by yargs.
> feat: expose camelCase and decamelize helpers

- package.json
It breaks `@types/yargs` for `yargs-parser` to ship types. This is [disruptive to the community](https://github.com/googleapis/nodejs-rcloadenv/pull/205).
> refactor!: do not ship type definitions

- README.md
- lib/yargs-parser-types.ts
- lib/yargs-parser.ts
- test/yargs-parser.cjs
Adds the `parse-positional-numbers` which allows the coercion of positional arguments that look like numbers to be configured independently from keys that look like numbers.
Refs https://github.com/yargs/yargs/issues/1758
> feat: adds parse-positional-numbers configuration

- browser.js
- deno.ts
- lib/index.ts
- lib/string-utils.ts
- lib/yargs-parser-types.ts
- lib/yargs-parser.ts
- test/deno/yargs-test.ts
- test/string-utils.cjs
Exports the looksLikeNumber helper, for the benefit of yargs.
> feat(string-utils): export looksLikeNumber helper

- lib/yargs-parser.ts
- test/yargs-parser.cjs
Numeric coercion was not being applied for positionals when `unknown-options-as-args` was `true`.
> fix(unknown-options-as-args): convert positionals that look like numbers

- deno.ts
In version 1.4 Deno adopted;
- the tsconfig setting [importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) - https://github.com/denoland/deno/pull/7413
This requires the use of;
- type only imports for values which are only used as types (`importsNotUsedAsValues`)
I've added more details at https://github.com/yargs/yargs/issues/1771.
related prs:
- yargs https://github.com/yargs/yargs/pull/1772
- y18n https://github.com/yargs/y18n/pull/100
---
While creating this pr, I was unable to get run the `yarn fix` command, this seems to be an unrelated issue though.
```sh
$ standardx --fix '**/*.ts' && standardx --fix '**/*.js' && standardx --fix '**/*.cjs'
standardx: Unexpected linter output:
Error: Failed to load config "standard" to extend from.
Referenced …
```
> fix(deno): update types for deno ^1.4.0

- lib/string-utils.ts
- test/string-utils.cjs
PR to fix issue https://github.com/yargs/yargs-parser/issues/345
> #345 do not lowercase camel cased string

- lib/yargs-parser.ts
- test/yargs-parser.cjs
If `populate--` has been set, then `--` should be coerced into an array.
Fixes: https://github.com/yargs/yargs/issues/1869
> fix(populate--): -- should always be array

- README.md
On my end:
```console
$ node -e 'console.log(require("yargs-parser")(process.argv.slice(1)))' 99.3
{ _: [ 99.3 ] }
```
Not sure why it is 99 in the [README](https://github.com/yargs/yargs-parser/blame/9cec00a622251292ffb7dce6f78f5353afaa0d4c/README.md#L255), seems to me like a typo.
Also updated all the example snippets to use the correct language code "console" (which is for shell script and their output) instead of "sh" (which is for shell script only). [[rendered preview](https://github.com/zypA13510/yargs-parser/blob/patch-1/README.md)]
> docs: correct typo in readme examples

- lib/index.ts
- lib/string-utils.ts
- lib/tokenize-arg-string.ts
- lib/yargs-parser-types.ts
- lib/yargs-parser.ts
This change allows automated extraction of the proper license attributions when bundling the contents. See [closure compiler docs as an example](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#license-preserve-description). The format is also [recognized by terser](https://webpack.js.org/plugins/terser-webpack-plugin/#extractcomments).
Fixes #369
> Add license comments to all source files

- index.js
- test/yargs-parser.js
back-port #394 to 15.x release line.
> fix(perf): address slow parse when using unknown-options-as-args

- .github/workflows/release-please.yml
- lib/yargs-parser.ts
- test/yargs-parser.cjs
Addresses: https://github.com/yargs/yargs/issues/1324
Inner quotes are handled differently by `parse`, depending on the `argsInput` argument's type.
`tokenizeArgString` wraps `argString` with extra quotes if it is a string.
`tokenizeArgString`  does not do the same for `argString`, if it is an array.
The first code block in `processValue` removes quotes from the value. 
If parse was given a string, extra quotes are added (tokenizeArgString) and then removed (processValue).
If parse was given an array, quotes are removed (processValue). This causes loss of inner quotes.
logs for string with inner quotes
```
{ argsInput: 'cmd --foo ""Hello"" --bar ""World"" --baz "":)""' }
during tokenizeArgString 
{ 
argString: 'cmd --foo ""Hello"" --bar ""World"" --baz "":)""' }
args: [  'cmd',  '--foo', …
```
> fix: parser should preserve inner quotes

- lib/yargs-parser.ts
- test/yargs-parser.cjs
Closes #437
The test case included in this PR has a simple reproduction of a scenario I've encountered where I want parse all options up to a non-option. All options after this argument should be considered unknown, including `--`.
Essentially, the use case that this accounts for is when a CLI provides two ways to indicate that the remainder of the argument list should not be parsed: by passing a non-option argument (enabling `halt-at-non-option`), or by passing `--` (enabling `populate--`). In addition to this, unknown options provided before the script are collected separately by enabling `unknown-options-as-args`. In my use case, these unknown options are Node.js CLI args that I forward to a child process.
> fix(halt-at-non-option): prevent known args from being parsed when "unknown-options-as-args" is enabled

- .nycrc
- lib/index.ts
Closes #447 by using `process.versions.node` for testing the version. The only difference between these values is the `v` prefix, so it's not as trivial as swapping a variable. Also, just in case `process.versions` is somehow not set, this falls back to previous behavior.
With this change in place, Bun should be able to import yargs.
> fix: node version check now uses process.versions.node
